import pandas as pd

from database import get_engine


def get_investigation_queue():

    """
    Retrieve investigation cases generated by the PostgreSQL
    analytics pipeline.
    """

    engine = get_engine()

    query = """
        SELECT *
        FROM analytics_investigation_queue
        ORDER BY priority_score DESC, month;
    """

    df = pd.read_sql(query, engine)

    return df
def get_top_investigation_case():
    """
    Return the highest-priority investigation case.
    """

    df = get_investigation_queue()

    if df.empty:
        return None

    return df.iloc[0].to_dict()
def get_case_history(region, product_category_name):

    """
    Retrieve historical revenue and inventory information
    for a specific region and product category.
    """

    engine = get_engine()

    query = """
        SELECT
            month,
            region,
            product_category_name,
            revenue,
            expected_revenue,
            revenue_deviation_pct,
            current_stock,
            reorder_level,
            stock_change_pct,
            inventory_status,
            business_signal,
            priority_score,
            priority_level
        FROM analytics_investigation_queue
        WHERE region = %(region)s
          AND product_category_name = %(category)s
        ORDER BY month;
    """

    params = {
        "region": region,
        "category": product_category_name
    }

    return pd.read_sql(query, engine, params=params)
def analyze_case_history(history, target_month):
    """
    Analyze the selected case against its available historical baseline.
    """

    if history.empty:
        return None

    baseline = history[history["month"] < target_month]

    if baseline.empty:
        return None

    analysis = {
        "historical_months": len(baseline),

        "avg_revenue_deviation": baseline[
            "revenue_deviation_pct"
        ].mean(),

        "median_revenue_deviation": baseline[
            "revenue_deviation_pct"
        ].median(),

        "avg_stock_change": baseline[
            "stock_change_pct"
        ].mean(),

        "median_stock_change": baseline[
            "stock_change_pct"
        ].median(),

        "target_revenue_deviation": history.loc[
            history["month"] == target_month,
            "revenue_deviation_pct"
        ].iloc[0],

        "target_stock_change": history.loc[
            history["month"] == target_month,
            "stock_change_pct"
        ].iloc[0]
    }

    return analysis
def calculate_z_scores(history, target_month):
    """
    Calculate historical standard deviation and z-scores
    for the selected investigation case.
    """

    if history.empty:
        return None

    baseline = history[history["month"] < target_month]

    if len(baseline) < 2:
        return None

    target = history[history["month"] == target_month]

    if target.empty:
        return None

    # Historical statistics
    revenue_mean = baseline["revenue_deviation_pct"].mean()
    revenue_std = baseline["revenue_deviation_pct"].std()

    stock_mean = baseline["stock_change_pct"].mean()
    stock_std = baseline["stock_change_pct"].std()

    target_revenue = target["revenue_deviation_pct"].iloc[0]
    target_stock = target["stock_change_pct"].iloc[0]

    # Avoid division by zero
    revenue_z_score = (
        (target_revenue - revenue_mean) / revenue_std
        if revenue_std != 0
        else 0
    )

    stock_z_score = (
        (target_stock - stock_mean) / stock_std
        if stock_std != 0
        else 0
    )

    return {
        "revenue_mean": revenue_mean,
        "revenue_std": revenue_std,
        "revenue_z_score": revenue_z_score,

        "stock_mean": stock_mean,
        "stock_std": stock_std,
        "stock_z_score": stock_z_score
    }

    """
    Analyze the distribution of revenue and inventory behavior
    across all available region/category/month observations.
    """

    engine = get_engine()

    query = """
        SELECT
            deviation_pct,
            stock_change_pct
        FROM analytics_business_signal
        WHERE deviation_pct IS NOT NULL
          AND stock_change_pct IS NOT NULL;
    """

    df = pd.read_sql(query, engine)

    if df.empty:
        return None

    revenue_stats = df["deviation_pct"].describe(
        percentiles=[0.05, 0.10, 0.90, 0.95]
    )

    stock_stats = df["stock_change_pct"].describe(
        percentiles=[0.05, 0.10, 0.90, 0.95]
    )

    return {
        "observation_count": len(df),
        "revenue_stats": revenue_stats,
        "stock_stats": stock_stats
    }

    """
    Inspect revenue-deviation patterns across all observations.
    """

    engine = get_engine()

    query = """
        SELECT
            month,
            region,
            product_category_name,
            deviation_pct,
            driver_status
        FROM analytics_business_signal
        ORDER BY deviation_pct;
    """

    df = pd.read_sql(query, engine)

    if df.empty:
        return None

    return df
def build_hybrid_assessment(top_case, z_scores):
    """
    Combine SQL business severity with statistical context.

    SQL scores represent business severity.
    Z-scores represent statistical abnormality.
    """

    if top_case is None or z_scores is None:
        return None

    def classify_z_score(z_score):
        if z_score <= -3:
            return "EXTREME"
        elif z_score <= -2:
            return "UNUSUAL"
        else:
            return "NORMAL"

    revenue_status = classify_z_score(
        z_scores["revenue_z_score"]
    )

    inventory_status = classify_z_score(
        z_scores["stock_z_score"]
    )

    if (
        top_case["inventory_score"]
        > top_case["revenue_score"]
    ):
        dominant_signal = "INVENTORY"

    elif (
        top_case["revenue_score"]
        > top_case["inventory_score"]
    ):
        dominant_signal = "REVENUE"

    elif inventory_status == "EXTREME":
        dominant_signal = "INVENTORY"

    elif revenue_status == "EXTREME":
        dominant_signal = "REVENUE"

    else:
        dominant_signal = "COMBINED"

    return {
        "business_priority": top_case["priority_level"],
        "business_score": top_case["priority_score"],

        "revenue_assessment": {
            "business_score": top_case["revenue_score"],
            "z_score": z_scores["revenue_z_score"],
            "statistical_status": revenue_status
        },

        "inventory_assessment": {
            "business_score": top_case["inventory_score"],
            "z_score": z_scores["stock_z_score"],
            "statistical_status": inventory_status
        },

        "reorder_score": top_case["reorder_score"],

        "dominant_signal": dominant_signal
    }
def build_evidence(top_case, analysis, z_scores, hybrid):
    """
    Build a structured evidence package for the investigation case.

    Evidence contains observable facts and comparisons.
    It does not make causal claims.
    """

    if (
        top_case is None
        or analysis is None
        or z_scores is None
        or hybrid is None
    ):
        return None

    evidence = {
        "case": {
            "month": top_case["month"],
            "region": top_case["region"],
            "product_category_name": top_case[
                "product_category_name"
            ]
        },

        "business_evidence": {
            "priority_level": top_case["priority_level"],
            "priority_score": top_case["priority_score"],
            "revenue_score": top_case["revenue_score"],
            "inventory_score": top_case["inventory_score"],
            "reorder_score": top_case["reorder_score"]
        },

        "revenue_evidence": {
            "revenue": top_case["revenue"],
            "expected_revenue": top_case["expected_revenue"],
            "revenue_deviation_pct": top_case[
                "revenue_deviation_pct"
            ],
            "historical_average_deviation": analysis[
                "avg_revenue_deviation"
            ],
            "historical_median_deviation": analysis[
                "median_revenue_deviation"
            ],
            "z_score": z_scores["revenue_z_score"],
            "statistical_status": hybrid[
                "revenue_assessment"
            ]["statistical_status"]
        },

        "inventory_evidence": {
            "current_stock": top_case["current_stock"],
            "reorder_level": top_case["reorder_level"],
            "stock_change_pct": top_case[
                "stock_change_pct"
            ],
            "historical_average_change": analysis[
                "avg_stock_change"
            ],
            "historical_median_change": analysis[
                "median_stock_change"
            ],
            "z_score": z_scores["stock_z_score"],
            "statistical_status": hybrid[
                "inventory_assessment"
            ]["statistical_status"],
            "below_reorder": top_case["below_reorder"],
            "inventory_status": top_case[
                "inventory_status"
            ]
        },

        "cross_signal_evidence": {
            "revenue_declined": (
                top_case["revenue_deviation_pct"] < 0
            ),
            "inventory_declined": (
                top_case["stock_change_pct"] < 0
            ),
            "same_case_period": True,
            "dominant_signal": hybrid[
                "dominant_signal"
            ]
        }
    }

    return evidence
def calculate_hypothesis_confidence(hypothesis, evidence,nlp_result):
    """
    Calculate evidence-based confidence for an LLM-generated
    hypothesis.

    The LLM generates the hypothesis.
    Python independently evaluates the available evidence.
    """

    if hypothesis is None or evidence is None or nlp_result is None:
        return None

    revenue = evidence["revenue_evidence"]
    inventory = evidence["inventory_evidence"]
    cross_signal = evidence["cross_signal_evidence"]
    business = evidence["business_evidence"]

    hypothesis_type = hypothesis.type.lower()
    statement = hypothesis.statement.lower()

    relationship = nlp_result["relationship"]
    causal_claim = nlp_result["causal_claim"]
    certainty = nlp_result["certainty"]
    signals = nlp_result["signals"]

    supporting_score = 0
    weakening_score = 0
    evidence_breakdown = []

    # ==================================================
    # INVENTORY-RELATED HYPOTHESIS
    # ==================================================

    inventory_related = (
        "inventory" in hypothesis_type
        or "stock" in hypothesis_type
        or "inventory" in statement
        or "stock" in statement
    )

    revenue_impact = (
        "revenue" in hypothesis_type
        or "revenue" in statement
        or "sales" in statement
    )

    # ==================================================
    # 1. INVENTORY + REVENUE HYPOTHESIS
    # ==================================================

    if inventory_related and revenue_impact:

        # Extreme inventory anomaly
        if inventory["statistical_status"] == "EXTREME":

            supporting_score += 3

            evidence_breakdown.append(
                (
                    "Inventory statistical status is EXTREME",
                    +3
                )
            )

        # Severe inventory decline
        if inventory["stock_change_pct"] <= -30:

            supporting_score += 2

            evidence_breakdown.append(
                (
                    "Inventory declined by more than 30%",
                    +2
                )
            )

        # Revenue below expected
        if revenue["revenue_deviation_pct"] < 0:

            supporting_score += 1

            evidence_breakdown.append(
                (
                    "Revenue is below expected",
                    +1
                )
            )

        # Same-period relationship
        if cross_signal["same_case_period"]:

            supporting_score += 2

            evidence_breakdown.append(
                (
                    "Revenue and inventory changes "
                    "occurred in the same period",
                    +2
                )
            )

        # But causation is not established
        weakening_score += 2

        evidence_breakdown.append(
            (
                "Evidence does not establish that "
                "inventory caused the revenue decline",
                -2
            )
        )

        # Revenue is statistically normal
        if revenue["statistical_status"] == "NORMAL":

            weakening_score += 1

            evidence_breakdown.append(
                (
                    "Revenue deviation is statistically NORMAL",
                    -1
                )
            )

    # ==================================================
    # 2. STATISTICAL HYPOTHESIS
    # ==================================================

    elif (
        "statistical" in hypothesis_type
        or "statistical" in statement
        or "normal" in hypothesis_type
        or "normal" in statement
        or "anomaly" in hypothesis_type
        or "anomaly" in statement
    ):

        # Revenue normal
        if revenue["statistical_status"] == "NORMAL":

            supporting_score += 3

            evidence_breakdown.append(
                (
                    "Revenue deviation is statistically NORMAL",
                    +3
                )
            )

        # Inventory extreme
        if inventory["statistical_status"] == "EXTREME":

            supporting_score += 3

            evidence_breakdown.append(
                (
                    "Inventory deviation is statistically EXTREME",
                    +3
                )
            )

        # Different statistical severity
        if (
            revenue["statistical_status"]
            != inventory["statistical_status"]
        ):

            supporting_score += 2

            evidence_breakdown.append(
                (
                    "Revenue and inventory have different "
                    "statistical severity",
                    +2
                )
            )

        # Inventory dominant
        if cross_signal["dominant_signal"] == "INVENTORY":

            supporting_score += 2

            evidence_breakdown.append(
                (
                    "Inventory is the dominant signal",
                    +2
                )
            )

    # ==================================================
    # 3. PURE INVENTORY HYPOTHESIS
    # ==================================================

    elif inventory_related:

        if inventory["statistical_status"] == "EXTREME":

            supporting_score += 3

            evidence_breakdown.append(
                (
                    "Inventory statistical status is EXTREME",
                    +3
                )
            )

        if inventory["stock_change_pct"] <= -30:

            supporting_score += 2

            evidence_breakdown.append(
                (
                    "Inventory declined by more than 30%",
                    +2
                )
            )

        if cross_signal["dominant_signal"] == "INVENTORY":

            supporting_score += 2

            evidence_breakdown.append(
                (
                    "Inventory is the dominant signal",
                    +2
                )
            )

    # ==================================================
    # 4. UNKNOWN / UNSUPPORTED HYPOTHESIS
    # ==================================================

    else:

        # We don't have a deterministic mapping for this
        # type of hypothesis.

        supporting_score += 1

        evidence_breakdown.append(
            (
                "Some case evidence is available",
                +1
            )
        )

        weakening_score += 2

        evidence_breakdown.append(
            (
                "Hypothesis cannot be directly evaluated "
                "from the structured evidence",
                -2
            )
        )

    # ==================================================
    # FINAL CONFIDENCE
    # ==================================================

    total_score = (
        supporting_score +
        weakening_score
    )

    if total_score == 0:

        return {
            "confidence_score": 0,
            "confidence_level": "INSUFFICIENT",
            "supporting_score": 0,
            "weakening_score": 0,
            "evidence_breakdown": evidence_breakdown
        }

    confidence_score = (
        supporting_score / total_score
    )

    if confidence_score >= 0.75:

        confidence_level = "HIGH"

    elif confidence_score >= 0.50:

        confidence_level = "MEDIUM"

    else:

        confidence_level = "LOW"

    return {
        "confidence_score": round(
            confidence_score,
            2
        ),
        "confidence_level": confidence_level,
        "supporting_score": supporting_score,
        "weakening_score": weakening_score,
        "evidence_breakdown": evidence_breakdown
    }